namespace FSH.Modules.Profile.Contracts.Dtos;

public sealed record ProfileDto(
    Guid Id,
    string Name,
    string Slug,
    string LastName,
    string FirstName,
    string MiddleName,
    int PersonnelNumber,
    string? CodePerson,
    string? Email,
    string? Login,
    string? AdSid,
    DateTime? DateBirth,
    DateTime? DateHire,
    DateTime? DateDismiss,
    int Sex,
    bool IsBoss,
    string? TypeEmployment,
    string? Staffing,
    string? City,
    string? Category,
    string? PhoneMobile,
    bool PhoneMobileAllowShow,
    string? PhoneWork,
    string? Division,
    string? Place,
    string? WtHcmId,
    bool IsDecret,
    bool IsMobilization,
    int Subordinates,
    string? Information,
    string? Description,
    Guid PositionId,
    Guid SubdivisionId,
    Guid HierarchyId,
    bool IsActive,
    // ThumbnailUrl — projection of the cover image's URL; null when the product has no images.
    // Derived server-side from the Images collection so list views don't need to ship Images.
    string? ThumbnailUrl,
    IReadOnlyList<ProfileImageDto> Images,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc,
    DateTimeOffset? DeletedOnUtc = null,
    string? DeletedBy = null);
